export const ROUTER_READY = 'ROUTER_READY';
export const SKIP_WELCOME_SCREENS = 'SKIP_WELCOME_SCREENS';
export const FACEBOOK_CONNECT = 'FACEBOOK_CONNECT';
export const FACEBOOK_LOGIN = 'FACEBOOK_LOGIN';
export const FACEBOOK_CONNECT_IGNORED = 'FACEBOOK_CONNECT_IGNORED';
export const FACEBOOK_CONNECT_FAILED = 'FACEBOOK_CONNECT_FAILED';
export const FACEBOOK_CONNECT_IN_PROGRESS = 'FACEBOOK_CONNECT_IN_PROGRESS';

export const OPEN_ADD_NEW_MODAL = 'OPEN_ADD_NEW_MODAL';
export const CLOSE_ADD_NEW_MODAL = 'CLOSE_ADD_NEW_MODAL';

export const RECORDING_PERMISSIONS_DENIED = 'RECORDING_PERMISSIONS_DENIED';
export const RECORDING_PERMISSIONS_GRANTED = 'RECORDING_PERMISSIONS_GRANTED';

export const FORM_ORIGINAL_CHANGED = 'FORM_ORIGINAL_CHANGED';
export const FORM_TRANSLATED_CHANGED = 'FORM_TRANSLATED_CHANGED';

export const ADD_NEW_PHRASE = 'ADD_NEW_PHRASE';
export const ADD_SHARED_PHRASE = 'ADD_SHARED_PHRASE';
export const ADD_SHARED_PHRASES = 'ADD_SHARED_PHRASES';
export const DELETE_PHRASE = 'DELETE_PHRASE';
export const SHARE_PHRASE = 'SHARE_PHRASE';
export const SHARE_ALL_PHRASES = 'SHARE_ALL_PHRASES';
export const DATA_LOADING = 'DATA_LOADING';
export const DATA_LOADED = 'DATA_LOADED';
