export const WELCOME_SCREENS_SKIPPED = 'WELCOME_SCREENS_SKIPPED';

export const MAIN_SCREEN_ITEM_TAPPED = 'MAIN_SCREEN_ITEM_TAPPED';
export const MAIN_SCREEN_LOAD_MORE_ITEMS = 'MAIN_SCREEN_LOAD_MORE_ITEMS';
export const MAIN_SCREEN_REFRESH = 'MAIN_SCREEN_REFRESH';

export const OPEN_ADD_NEW_MODAL = 'OPEN_ADD_NEW_MODAL';
export const CLOSE_ADD_NEW_MODAL = 'CLOSE_ADD_NEW_MODAL';

export const RECORDING_PERMISSIONS_DENIED = 'RECORDING_PERMISSIONS_DENIED';
export const RECORDING_PERMISSIONS_GRANTED = 'RECORDING_PERMISSIONS_GRANTED';

export const FORM_ORIGINAL_CHANGED = 'FORM_ORIGINAL_CHANGED';
export const FORM_TRANSLATED_CHANGED = 'FORM_TRANSLATED_CHANGED';

export const ADD_NEW_PHRASE = 'ADD_NEW_PHRASE';
export const DELETE_PHRASE = 'DELETE_PHRASE';
