export const WELCOME_SCREENS_SKIPPED = 'WELCOME_SCREENS_SKIPPED';

export const MAIN_SCREEN_ITEM_TAPPED = 'MAIN_SCREEN_ITEM_TAPPED';
export const MAIN_SCREEN_LOAD_MORE_ITEMS = 'MAIN_SCREEN_LOAD_MORE_ITEMS';
export const MAIN_SCREEN_REFRESH = 'MAIN_SCREEN_REFRESH';

export const OPEN_ADD_NEW_MODAL = 'OPEN_ADD_NEW_MODAL';
export const CLOSE_ADD_NEW_MODAL = 'CLOSE_ADD_NEW_MODAL';

export const RECORDING_PERMISSIONS_DENIED = 'RECORDING_PERMISSIONS_DENIED';
export const RECORDING_PERMISSIONS_GRANTED = 'RECORDING_PERMISSIONS_GRANTED';
